### ISSUE TITLE
Plotting with refinement >1 fails

### ISSUE THREAD

**Issue by bbiswas-plasma** [piScope/PetraM_Base#24]
I tried to export edge data from a EM2Da solution. Solution is of element order 2.

When refinement is increased from 1 -> 2, and "Export" is clicked, the following error appears:
"
Failed to evauate expression
AssertionError: Traceback (most recent call last):
  File "<string>", line 132, in <module>
  File "/home/shiraiwa/twopi_roots/20200114/lib/python3.6/site-packages/PetraM_Base-0.9.6-py3.6.egg/petram/sol/evaluator_mp.py", line 443, in eval
    assert False, x2
AssertionError: Traceback (most recent call last):
  File "/home/shiraiwa/twopi_roots/20200114/lib/python3.6/site-packages/PetraM_Base-0.9.6-py3.6.egg/petram/sol/evaluator_mp.py", line 254, in eval
    v, c, a = o.eval(expr, solvar, phys, **kwargs)
  File "/home/shiraiwa/twopi_roots/20200114/lib/python3.6/site-packages/PetraM_Base-0.9.6-py3.6.egg/petram/sol/edge_nodal_evaluator.py", line 137, in eval
    from nodal_refinement import refine_edge_data
ModuleNotFoundError: No module named 'nodal_refinement'
"

**Comment by sshiraiwa** [comment]
Thanks. At glance, this looks just an overlooked syntax change required for python3. But, 
there is something wrong in plotting the refined data. I will look into it more.

**Comment by bbiswas-plasma** [comment]
Plotting/exporting solutions with refinement >1 works now.
