### ISSUE TITLE
Petra-M not opening on PSFC MFE workstations

### ISSUE THREAD

**Issue by bbiswas-plasma** [piScope/PetraM_Base#66]
Hello,
I tried to launch Petra-M today on mfews01 and mferws01 using the command:
`petram()`
in piscope. I got the following error message:
`
script exectuion failed
Traceback (most recent call last):
  File "/home/shiraiwa/twopi_roots/20190713_py3/src/piScope/python/ifigure/mto/py_script.py", line 163, in run_script
    exec(self._script_co, lc, lc)
  File "/home/biswas/scratch/.piscope_tmp/piscope_biswas/mfews01.pid5005/###untitled_47ad8ef4950282a2939a3f163ad18aa2/proj/model1/mfem/scripts/helpers/open_gui.py", line 14, in <module>
    obj.get_pymodel().mfembook.Open(MFEMViewer)
  File "/home/shiraiwa/twopi_roots/20190713_py3/src/piScope/python/ifigure/widgets/at_wxthread.py", line 27, in checker
    return func(*args, **kargs)
  File "/home/shiraiwa/twopi_roots/20190713_py3/src/piScope/python/ifigure/mto/fig_book.py", line 337, in Open
    v.onClose()
AttributeError: 'NoneType' object has no attribute 'onClose'

<petram.pi.shell_commands.PetraMHelper object at 0x7fa4f417bc18>
'

I'm running the "/home/shiraiwa/twopi_roots/20190713_py3/bin/activate_twopi" script before launching piscope.
I haven't run into a problem launching Petra-M before. Although, I haven't used it in a few weeks, so perhaps the protocol for launching it has changed since then.
Thanks.

**Comment by bbiswas-plasma** [comment]
It's working now. Thanks.
