### ISSUE TITLE
the order set in model.py input file does not reflect in the simulation

### ISSUE THREAD

**Issue by mortezah** [piScope/PetraM_Base#76]
@sshiraiwa 

I have recently updated all the PetraM libraries and ran one of my old runs (using the `model.py` that I had) again with the updated libraries. Even though in the `model.py` file the order of the finite element space is set to 2, it seems that that does not reflect in the simulation (that is during the simulation the default order of 1 is used). 

Has the format of `model.py` changed recently?

I have tried to recreate that model file by setting up the problem in piScope again but I am having trouble running piScope with the following error. Any idea what might be causing this?

```
/lore/hakimm2/projects/petram/twopi_scorecrhel7_python38_dev3/src/piScope/bin/piscope.sh
('removing past crush dir', '/lore/hakimm2/tmp/piscope/piscope_hakimm2/scrabble.pid31787')
reading extra color maps
Traceback (most recent call last):
  File "/lore/hakimm2/projects/petram/twopi_scorecrhel7_python38_dev3/src/piScope/python/piscope.py", line 29, in <module>
    from ifigure.ifigure_app import ifigure_app, MyApp
  File "/lore/hakimm2/projects/petram/twopi_scorecrhel7_python38_dev3/src/piScope/python/ifigure/ifigure_app.py", line 22, in <module>
    import ifigure.server
  File "/lore/hakimm2/projects/petram/twopi_scorecrhel7_python38_dev3/src/piScope/python/ifigure/server.py", line 35, in <module>
    import ifigure.events
  File "/lore/hakimm2/projects/petram/twopi_scorecrhel7_python38_dev3/src/piScope/python/ifigure/events.py", line 18, in <module>
    from ifigure.widgets.book_viewer import BookViewer
  File "/lore/hakimm2/projects/petram/twopi_scorecrhel7_python38_dev3/src/piScope/python/ifigure/widgets/book_viewer.py", line 42, in <module>
    from ifigure.widgets.canvas.ifigure_canvas import ifigure_canvas
  File "/lore/hakimm2/projects/petram/twopi_scorecrhel7_python38_dev3/src/piScope/python/ifigure/widgets/canvas/ifigure_canvas.py", line 55, in <module>
    from ifigure.widgets.navibar2 import navibar
  File "/lore/hakimm2/projects/petram/twopi_scorecrhel7_python38_dev3/src/piScope/python/ifigure/widgets/navibar2.py", line 9, in <module>
    from ifigure.mto.fig_axes import FigInsetAxes
  File "/lore/hakimm2/projects/petram/twopi_scorecrhel7_python38_dev3/src/piScope/python/ifigure/mto/fig_axes.py", line 39, in <module>
    from ifigure.mto.fig_plot import FigPlot
  File "/lore/hakimm2/projects/petram/twopi_scorecrhel7_python38_dev3/src/piScope/python/ifigure/mto/fig_plot.py", line 25, in <module>
    from ifigure.matplotlib_mod.art3d_gl import Line3DCollectionGL, LineGL
  File "/lore/hakimm2/projects/petram/twopi_scorecrhel7_python38_dev3/src/piScope/python/ifigure/matplotlib_mod/art3d_gl.py", line 430, in <module>
    class AxesImageGL(ArtGL, AxesImage):
  File "/lore/hakimm2/projects/petram/twopi_scorecrhel7_python38_dev3/lib/python3.8/site-packages/matplotlib/artist.py", line 119, in __init_subclass__
    cls._update_set_signature_and_docstring()
  File "/lore/hakimm2/projects/petram/twopi_scorecrhel7_python38_dev3/lib/python3.8/site-packages/matplotlib/artist.py", line 139, in _update_set_signature_and_docstring
    *[Parameter(prop, Parameter.KEYWORD_ONLY, default=_UNSET)
  File "/lore/hakimm2/projects/petram/twopi_scorecrhel7_python38_dev3/lib/python3.8/site-packages/matplotlib/artist.py", line 139, in <listcomp>
    *[Parameter(prop, Parameter.KEYWORD_ONLY, default=_UNSET)
  File "/lore/hakimm2/opt/local/lib/python3.8/inspect.py", line 2513, in __init__
    raise ValueError('{!r} is not a valid parameter name'.format(name))
ValueError: '3dpath' is not a valid parameter name
```

**Comment by sshiraiwa** [comment]
Order field is not directly editable anymore because in the recent version it dynamically evaluates FEM element order from order_txt attribute. 
Can you try adding order_txt attribute to the object. Something like
`obj17.order_txt = '2'`

**Comment by sshiraiwa** [comment]
Another question. Did you update piScope too, and what is the version of wxWidget? With 4.1.0, I don't see this issue.

**Comment by mortezah** [comment]
@sshiraiwa 

setting the `order_txt` does not seem to fix the problem. I guess my best chance is to get `piScope` to run and re-make the problem in PetraM and get a new `model.py`. 

I am using python3.8. Do you think moving to the latest version of python could fix the problem with `piScope`?
